AWSTemplateFormatVersion: '2010-09-09'
Description: My first CloudFormation stack - a single s3 bucket.


Resources:
  MyFirstBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
